apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp-leumi
  labels:
    role: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: app
        image: "dhpdockerhub/hi-leumi-py"
        resources:
          requests:
            cpu: 10m
---    
apiVersion: v1
kind: Service
metadata:
  name: hi-leumi
spec:
  selector:
    role: app
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 32000
  type: NodePort
